//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOA_DON
    {
        public int ID { get; set; }
        public Nullable<int> HOA_DON_ID { get; set; }
        public Nullable<int> SAN_PHAM_ID { get; set; }
        public Nullable<int> SO_LUONG_MUA { get; set; }
        public Nullable<double> DON_GIA_MUA { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public Nullable<byte> TRANG_THAI { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
