//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        public int MA_SP { get; set; }
        public string TEN_SP { get; set; }
        public string MO_TA { get; set; }
        public Nullable<double> GIA { get; set; }
        public Nullable<int> MA_LSP { get; set; }
        public string HINH_ANH { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
    
        public virtual LOAI_SAN_PHAM LOAI_SAN_PHAM { get; set; }
    }
}
