//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIN_TUC
    {
        public int MA_TT { get; set; }
        public string TIEU_DE { get; set; }
        public string NOI_DUNG { get; set; }
    }
}
